language: objective-c
osx_image: xcode9.2

before_install:
- pod install

branches:
  only:
  - master
  - development
  
script:
- xcodebuild clean build test -project TCCollections.xcodeproj -scheme TCCollections -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
